apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  replicas: 5
  selector:
    matchLabels:
      service: headless
  template:
    metadata:
      labels:
        service: headless
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
