apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      env:
        - name: NAME
          value: David
      ports:
        - containerPort: 80
