apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
    name: sleep
spec:
  containers:
    - name: sleep
      image: alpine:3.8
      command: #[ "sleep", "10" ]
        - "sleep"
        - "10"
      resources: {}
