apiVersion: apps/v1
kind: Deployment
metadata:
  name: octobercms
spec:
  selector:
    matchLabels:
      app: octobercms
  template:
    metadata:
      labels:
        app: octobercms
    spec:
      initContainers:
        - name: db
          image: aspendigital/octobercms
          command:
            - php
          args:
            - artisan
            - october:up
      containers:
        - name: octobercms
          image: aspendigital/octobercms
          resources: {}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: octobercms
