apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
  containers:
    - name: sleep
      image: busybox
      command:
        - sleep
      args:
        - "100000"
      resources: {}
      envFrom:
        - configMapRef:
            name: simple-config
      volumeMounts:
        - name: nginx-config
          mountPath: /my-config-map
