apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: content
      configMap:
        name: content
  containers:
    - name: sleep
      image: nginx:1.17.3
      resources: {}
      envFrom:
        - configMapRef:
            name: content
      volumeMounts:
        - name: content
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/virtual-host.conf
          subPath: virtual-host.conf
