apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: alpine:3.7
          command:
            - sleep
          args:
            - "100000"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
