apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeinfo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodeinfo
  template:
    metadata:
      labels:
        app: nodeinfo
    spec:
      containers:
        - name: nodeinfo
          image: functions/node-info
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
